apiVersion: batch/v1
kind: Job
metadata:
  name: uninstall-{{ include "designate-certmanager-webhook.fullname" . }}
  labels:
    app: {{ include "designate-certmanager-webhook.name" . }}
    chart: {{ include "designate-certmanager-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  namespace: default
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "designate-certmanager-webhook.fullname" . }}
      containers:
        - name: remove-apiservice
          image: bitnami/kubectl:latest
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - kubectl
          args:
            - delete
            - --ignore-not-found
            - apiservice
            - v1alpha1.acme.syseleven.de
---
# Grant cert-manager permission to validate using our apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "designate-certmanager-webhook.fullname" . }}:uninstall
  labels:
    app: {{ include "designate-certmanager-webhook.name" . }}
    chart: {{ include "designate-certmanager-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
rules:
  - apiGroups:
      - acme.syseleven.de
    resources:
      - '*'
    verbs:
      - 'create'
  - apiGroups:
      - apiregistration.k8s.io
    resources:
      - apiservices
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "designate-certmanager-webhook.fullname" . }}:uninstall
  labels:
    app: {{ include "designate-certmanager-webhook.name" . }}
    chart: {{ include "designate-certmanager-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "designate-certmanager-webhook.fullname" . }}:uninstall
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "designate-certmanager-webhook.fullname" . }}
    namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "designate-certmanager-webhook.fullname" . }}
  labels:
    app: {{ include "designate-certmanager-webhook.name" . }}
    chart: {{ include "designate-certmanager-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
  namespace: default
